###
POST http://localhost:8000/adapter-service/search

{
  "question": "毛泽东思想形成的时代背景是( )",
  "options": [
    "帝国主义战争与无产阶级革命成为时代主题", "和平与发展成为时代主题", "世界多极化成为时代主题", "经济全球化成为时代主题"
  ],
  "type": 0,
  "use":[
  {"name":"Tikuhai",
  "key":"*****"
  },
  {"name":"Enncy",
  "key":"*******"
  }]
  
}