###单选

POST http://localhost:8000/adapter-service/search

{
  "question": "毛泽东思想形成的时代背景是( )",
  "options": [
    "帝国主义战争与无产阶级革命成为时代主题",
    "和平与发展成为时代主题",
    "世界多极化成为时代主题",
    "经济全球化成为时代主题"
  ],
  "type": 0,
  "use": {
    "Tikuhai": {
      "key": "******"
    },
    "Enncy": {
      "token": "******"
    },
    "Like": {
      "token": "******"
    },
    "EveryAPI": {
      "token": "******"
    },
    "Wanneng":{
        "token":"******"
    },
    "Lemon":{}
  }
}

###多选
POST http://localhost:8000/adapter-service/search

{
  "question": "通过劳动教育，使学生能够理解和形成马克思主义劳动观，牢固树立（）的观念。",
  "options": [
    "A劳动最光荣",
    "B劳动最崇高",
    "C劳动最伟大",
    "D劳动最美丽"
  ],
  "type": 1,
  "use": {
    "Tikuhai": {
      "key": "******"
    },
    "Enncy": {
      "token": "******"
    },
    "Like": {
      "token": "******"
    },
    "EveryAPI": {
      "token": "******"
    },
    "Wanneng":{
        "token":"******"
    },
    "Lemon":{}
  }
}
